// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxarMYOHB4D0TG2qP-QLbKPY_EG1sHTIs',
    appId: '1:929662514832:web:a4c040c9209456797d0a15',
    messagingSenderId: '929662514832',
    projectId: 'takhti-f5878',
    authDomain: 'takhti-f5878.firebaseapp.com',
    storageBucket: 'takhti-f5878.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYGXbDp-7A5bnFcpW8jYymHgwiUUViNy0',
    appId: '1:929662514832:android:d73cae8d625858657d0a15',
    messagingSenderId: '929662514832',
    projectId: 'takhti-f5878',
    storageBucket: 'takhti-f5878.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsJiZh-biK0m4vIY5t6w-rNro5j0PSr90',
    appId: '1:929662514832:ios:6d475f2de3a2a7477d0a15',
    messagingSenderId: '929662514832',
    projectId: 'takhti-f5878',
    storageBucket: 'takhti-f5878.appspot.com',
    iosClientId: '929662514832-c7m03njhhs8kf0jns1s5arkksuobul91.apps.googleusercontent.com',
    iosBundleId: 'com.example.takhtiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsJiZh-biK0m4vIY5t6w-rNro5j0PSr90',
    appId: '1:929662514832:ios:e802c826a270a6e77d0a15',
    messagingSenderId: '929662514832',
    projectId: 'takhti-f5878',
    storageBucket: 'takhti-f5878.appspot.com',
    iosClientId: '929662514832-qi544bgqrc9m1jkcqsmk8m82lhle8ghi.apps.googleusercontent.com',
    iosBundleId: 'com.example.takhtiApp.RunnerTests',
  );
}
